[package]
name = "hi-interpreter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "hi"
path = "src/main.rs"

[dependencies]
hi-common = { path = "../hi-common" }
anyhow = "1.0.103"
chrono = "0.4.45"
clap = { version = "4.6.2", features = ["derive"] }
colored = "3.1.1"
inventory = "0.3.24"
rand = "0.10.2"
regex = "1.13.1"
rustyline = "18.0.1"
serde = "1.0.229"
serde_json = "1.0.151"
thiserror = "2.0.18"

[dev-dependencies]
stdio-override = "0.2.0"
tempfile = "3.27.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
