[package]
name = "hi-analyzer"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hi-common = { path = "../hi-common" }
hi-interpreter = { path = "../hi-interpreter" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"